/**
 * download-logos.js
 * Run once: node scripts/download-logos.js
 * Downloads all critical onboarding logos to /public/logos/ for offline support.
 */

import https from 'https';
import http from 'http';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = path.join(__dirname, '..', 'public', 'logos');

// ── All hardcoded domains used in onboarding/guider screens ──
const DOMAINS = [
  // Guider Step 1 (calendar preview)
  'netflix.com',
  'spotify.com',
  'amazon.com',
  'apple.com',
  'disneyplus.com',
  'hulu.com',
  'adobe.com',
  'figma.com',
  'slack.com',
  'google.com',
  'canva.com',
  'linkedin.com',
  'zoom.us',
  'medium.com',
  'github.com',
  // Guider Step 2 extras
  'notion.so',
  'chatgpt.com',
  // Guider Step 3 extras
  'youtube.com',
  'lovable.dev',
  // Believe page extras (most common — rest fall back to letter)
  'microsoft.com',
  'dropbox.com',
  'openai.com',
  'grammarly.com',
  'discord.com',
  'hotstar.com',
  // Landing page SVG animation (already mostly covered above)
];

function sanitizeFilename(domain) {
  // e.g. "zoom.us" → "zoom.us.png", "aws.amazon.com" → "aws.amazon.com.png"
  return domain.replace(/[^a-z0-9.\-]/gi, '_') + '.png';
}

function download(url, dest) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(dest);
    const protocol = url.startsWith('https') ? https : http;

    protocol.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, (response) => {
      // Handle redirects
      if (response.statusCode === 301 || response.statusCode === 302) {
        file.close();
        fs.unlinkSync(dest);
        return download(response.headers.location, dest).then(resolve).catch(reject);
      }

      if (response.statusCode !== 200) {
        file.close();
        fs.unlinkSync(dest);
        return reject(new Error(`HTTP ${response.statusCode} for ${url}`));
      }

      response.pipe(file);
      file.on('finish', () => {
        file.close();
        // Check if the file has valid content (> 100 bytes)
        const stats = fs.statSync(dest);
        if (stats.size < 100) {
          fs.unlinkSync(dest);
          reject(new Error(`File too small (${stats.size} bytes) — likely an error page`));
        } else {
          resolve();
        }
      });
    }).on('error', (err) => {
      file.close();
      if (fs.existsSync(dest)) fs.unlinkSync(dest);
      reject(err);
    });
  });
}

async function run() {
  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`✅ Created directory: ${OUTPUT_DIR}`);
  }

  let success = 0;
  let skipped = 0;
  let failed = 0;

  for (const domain of DOMAINS) {
    const filename = sanitizeFilename(domain);
    const dest = path.join(OUTPUT_DIR, filename);

    // Skip if already downloaded
    if (fs.existsSync(dest) && fs.statSync(dest).size > 100) {
      console.log(`⏭️  Already exists: ${filename}`);
      skipped++;
      continue;
    }

    const url = `https://icon.horse/icon/${domain}`;
    process.stdout.write(`⬇️  Downloading: ${domain} ... `);

    try {
      await download(url, dest);
      const size = (fs.statSync(dest).size / 1024).toFixed(1);
      console.log(`✅ OK (${size} KB)`);
      success++;
    } catch (err) {
      console.log(`❌ FAILED: ${err.message}`);
      failed++;
    }

    // Small delay to be polite to icon.horse
    await new Promise(r => setTimeout(r, 300));
  }

  console.log(`\n📦 Done! ${success} downloaded, ${skipped} skipped, ${failed} failed.`);
  console.log(`📁 Logos saved to: ${OUTPUT_DIR}`);

  // Generate the JS map file
  const mapEntries = DOMAINS
    .map(domain => {
      const filename = sanitizeFilename(domain);
      const fullPath = path.join(OUTPUT_DIR, filename);
      if (fs.existsSync(fullPath) && fs.statSync(fullPath).size > 100) {
        return `  '${domain}': '/logos/${filename}'`;
      }
      return null;
    })
    .filter(Boolean)
    .join(',\n');

  const mapContent = `// AUTO-GENERATED by scripts/download-logos.js — DO NOT EDIT MANUALLY
// Maps known domains to locally bundled logo paths for offline support.
export const LOCAL_LOGOS = {
${mapEntries}
};
`;

  const mapPath = path.join(__dirname, '..', 'src', 'features', 'logos', 'local-logos-map.js');
  fs.mkdirSync(path.dirname(mapPath), { recursive: true });
  fs.writeFileSync(mapPath, mapContent, 'utf8');
  console.log(`\n✏️  Generated logo map: ${mapPath}`);
}

run().catch(console.error);
